### ISSUE TITLE
photutils.test() is missing

### ISSUE THREAD

**Issue by svaverbe** [astropy/photutils#1043]
I am new to the package and tried to install photutils in Ubuntu linux under windows subsystem for linux.  The following script yields an error, since the test suite appears to be missing:

import numpy as np
import photutils
photutils.test()
hdu = photutils.datasets.load_star_image()  
image = hdu.data[500:700, 500:700].astype(float)  

python photutils.py
Traceback (most recent call last):
  File "photutils.py", line 2, in <module>
    import photutils
  File "/mnt/d/WD/photutils.py", line 3, in <module>
    photutils.test()
AttributeError: module 'photutils' has no attribute 'test'

Can anyone please provide some help with the right installation and the version consistent with the online documentation. 

Siegfried

**Comment by larrybradley** [comment]
@svaverbe Which version of photutils did you install and how did you install it (e.g. via pip or conda)?

**Comment by svaverbe** [comment]
I used pip.  Version 0.7.2 was installed successfully.

**Comment by larrybradley** [comment]
Do you have `pytest-astropy` installed (`pip install pytest-astropy`)?

**Comment by svaverbe** [comment]
Yes, that requirement is fullfilled.

**Comment by larrybradley** [comment]
Your error message shows:
```
import photutils
File "/mnt/d/WD/photutils.py", line 3, in
```

There is no `photutils.py` file in the `photutils` package.  It appears you are importing a module called `photutils.py` instead of the `photutils` package.

**Comment by svaverbe** [comment]
And that solves the first problem.  The test suite is now executed, but we have more messages:

python photutils-test.py
Traceback (most recent call last):
  File "photutils-test.py", line 3, in <module>
    photutils.test()
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/astropy/tests/runner.py", line 261, in test
    return runner.run_tests(**kwargs)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/astropy/tests/runner.py", line 606, in run_tests
    return super().run_tests(**kwargs)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/astropy/tests/runner.py", line 243, in run_tests
    return pytest.main(args=args, plugins=plugins)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/config/__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/config/__init__.py", line 258, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/config/__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/config/__init__.py", line 992, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/hypothesis/__init__.py", line 26, in <module>
    from hypothesis.core import example, find, given, reproduce_failure, seed
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/hypothesis/core.py", line 68, in <module>
    from hypothesis.internal.conjecture.engine import ConjectureRunner, sort_key
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/hypothesis/internal/conjecture/engine.py", line 41, in <module>
    from hypothesis.internal.conjecture.pareto import NO_SCORE, ParetoFront, ParetoOptimiser
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/hypothesis/internal/conjecture/pareto.py", line 22, in <module>
    from hypothesis.internal.conjecture.shrinker import sort_key
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/siegfried/anaconda3/envs/science/lib/python3.6/site-packages/hypothesis/internal/conjecture/shrinker.py", line 1449, in <module>
    @attr.s(slots=True, eq=False)
TypeError: attrs() got an unexpected keyword argument 'eq'

**Comment by larrybradley** [comment]
The above errors are coming from the `pytest` and `hypothesis` testings package, not `photutils`.  Perhaps try updating those packages?
