### ISSUE TITLE
Import error with photutils

### ISSUE THREAD

**Issue by ibusko** [astropy/photutils#1050]
This looks familiar to me, I think I've seen this in the past. It came back when I installed the latest version from sources.

`(photutils) bash-3.2$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import photutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/busko/Projects/photutils/photutils/__init__.py", line 17, in <module>
    from .aperture import *  # noqa
  File "/Users/busko/Projects/photutils/photutils/aperture/__init__.py", line 7, in <module>
    from .circle import *  # noqa
  File "/Users/busko/Projects/photutils/photutils/aperture/circle.py", line 15, in <module>
    from ..geometry import circular_overlap_grid
  File "/Users/busko/Projects/photutils/photutils/geometry/__init__.py", line 6, in <module>
    from .circular_overlap import *  # noqa
ModuleNotFoundError: No module named 'photutils.geometry.circular_overlap'
>>> 
`

**Comment by larrybradley** [comment]
That error is because the cython files aren't compiled.  Are you importing from within the python source directory?  If so, you'll need to do an in-place build.

**Comment by ibusko** [comment]
Indeed, now I remember. Thanks!
