### ISSUE TITLE
Freshly installed photutils throws error on import 

### ISSUE THREAD

**Issue by mfeldt** [astropy/photutils#1487]
Newly created conda environment python 3.9, installed photutils from conda, first thing I tried:

```
Python 3.9.16 (main, Jan 11 2023, 16:05:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from photutils import datasets        
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/miniconda3/envs/f36/lib/python3.9/site-packages/photutils/__init__.py", line 19, in <module>
    from .segmentation import *  # noqa
  File "/home/xxx/miniconda3/envs/f36/lib/python3.9/site-packages/photutils/segmentation/__init__.py", line 10, in <module>
    from .deblend import *  # noqa
  File "/home/xxx/miniconda3/envs/f36/lib/python3.9/site-packages/photutils/segmentation/deblend.py", line 13, in <module>
    from .detect import _make_binary_structure, _detect_sources
  File "/home/xxx/miniconda3/envs/f36/lib/python3.9/site-packages/photutils/segmentation/detect.py", line 20, in <module>
    @deprecated_renamed_argument('mask_value', None, '1.4', message='Use the '
TypeError: deprecated_renamed_argument() got an unexpected keyword argument 'message'


```

**Comment by larrybradley** [comment]
@mfeldt I cannot reproduce your error.  It appears that `photutils` is not currently installed in your conda environment (see your `conda list` output above).  Your conda environment is probably "shadowing" your base conda environment where an older version is installed.  Note that `photutils` is not available via the "default" `conda` channel, so you need to specify the `conda-forge` channel on the command-line (or have it set in your ~.condarc), e.g., `conda install photutils -c conda-forge`.

The specific error you are seeing `TypeError: deprecated_renamed_argument() got an unexpected keyword argument 'message'` indicates that the version of `photutils` that is being picked up is also using an old version of `astropy` (< 5.0).  The `message` keyword to `deprecated_renamed_argument` was introduced in astropy 5.0.  `photutils` has required `astropy >= 5.0` since version 1.4.0.  Somehow your conda environment is picking up an odd combination of `photutils` and `astropy`.  Please try `conda install photutils -c conda-forge`.  You can also check your photutils and astropy versions within python using:

```python
>>> import photutils
>>> photutils.__version__
>>> import astropy
>>> astropy.__version__
```

**Comment by mfeldt** [comment]
This is not what is happening. In my base environment, photutils are unavailable, so nothing is shadowing anywhere.

Also, the error message thrown clearly gives the file location as inside the active environment where I installed photutils to.

What I did however, was no the simple install I originally posted, but a 

`conda install -c astropy photutils`

So I guess that is the culprit of installing an outdated version.

**Comment by larrybradley** [comment]
The conda astropy channel hasn't been updated with the latest version of photutils, but that version (1.5.0) works fine as well. This works fine for me:
```
conda create -n myenv python=3.9
conda activate myenv
conda install photutils -c astropy
```

But `conda list` gives a very different output than the one you posted:
```
# Name                    Version                   Build  Channel
asdf                      2.10.0             pyhd8ed1ab_0    astropy
astropy                   5.1              py39h15b18c7_0    astropy
attrs                     22.1.0           py39hecd8cb5_0
black                     22.6.0           py39hecd8cb5_0
blas                      1.0                         mkl
blosc                     1.21.0               h8346a28_1
bottleneck                1.3.5            py39h67323c0_0
brotli                    1.0.9                hca72f7f_7
brotli-bin                1.0.9                hca72f7f_7
brunsli                   0.1                  h23ab428_0
bzip2                     1.0.8                h1de35cc_0
c-ares                    1.18.1               hca72f7f_0
ca-certificates           2023.01.10           hecd8cb5_0
certifi                   2022.12.7        py39hecd8cb5_0
cfitsio                   3.470                hbd21bf8_7
charls                    2.2.0                h23ab428_0
click                     8.0.4            py39hecd8cb5_0
cloudpickle               2.0.0              pyhd3eb1b0_0
contourpy                 1.0.5            py39haf03e11_0
coverage                  6.3.2            py39hca72f7f_0
cycler                    0.11.0             pyhd3eb1b0_0
cytoolz                   0.12.0           py39hca72f7f_0
dask-core                 2022.7.0         py39hecd8cb5_0
fftw                      3.3.9                h9ed2024_1
flit-core                 3.6.0              pyhd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               hd8bbffd_0
fsspec                    2022.11.0        py39hecd8cb5_0
giflib                    5.2.1                h6c40b1e_1
gwcs                      0.17.1             pyhd8ed1ab_0    astropy
hypothesis                6.29.3             pyhd3eb1b0_0
imagecodecs               2021.8.26        py39h0f85e6e_1
imageio                   2.19.3           py39hecd8cb5_0
importlib-metadata        4.11.3           py39hecd8cb5_0
importlib_metadata        4.11.3               hd3eb1b0_0
importlib_resources       5.2.0              pyhd3eb1b0_1
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2021.4.0          hecd8cb5_3538
jmespath                  0.10.0             pyhd3eb1b0_0
joblib                    1.1.1            py39hecd8cb5_0
jpeg                      9e                   hca72f7f_0
jsonschema                3.2.0              pyhd3eb1b0_2
jxrlib                    1.1                  haf1e3a3_2
kiwisolver                1.4.4            py39hcec6c5f_0
krb5                      1.19.4               hdba6334_0
lcms2                     2.12                 hf1fd2bf_0
lerc                      3.0                  he9d5cce_0
libaec                    1.0.4                hb1e8313_1
libbrotlicommon           1.0.9                hca72f7f_7
libbrotlidec              1.0.9                hca72f7f_7
libbrotlienc              1.0.9                hca72f7f_7
libcurl                   7.87.0               ha585b31_0
libcxx                    14.0.6               h9765a3e_0
libdeflate                1.8                  h9ed2024_5
libedit                   3.1.20221030         h6c40b1e_0
libev                     4.33                 h9ed2024_1
libffi                    3.4.2                hecd8cb5_6
libgfortran               5.0.0           11_3_0_hecd8cb5_28
libgfortran5              11.3.0              h9dfd629_28
libnghttp2                1.46.0               ha29bfda_0
libpng                    1.6.37               ha441bb4_0
libssh2                   1.10.0               h0a4fc7d_0
libtiff                   4.5.0                h2cd0358_0
libwebp                   1.2.4                h56c3ce4_0
libwebp-base              1.2.4                hca72f7f_0
libzopfli                 1.0.3                hb1e8313_0
llvm-openmp               14.0.6               h0dcd299_0
locket                    1.0.0            py39hecd8cb5_0
lz4-c                     1.9.4                hcec6c5f_0
matplotlib-base           3.6.2            py39h220de94_0
mkl                       2021.4.0           hecd8cb5_637
mkl-service               2.4.0            py39h9ed2024_0
mkl_fft                   1.3.1            py39h4ab4a9b_0
mkl_random                1.2.2            py39hb2f4e1b_0
munkres                   1.1.4                      py_0
mypy_extensions           0.4.3            py39hecd8cb5_1
ncurses                   6.3                  hca72f7f_3
networkx                  2.8.4            py39hecd8cb5_0
numpy                     1.23.5           py39he696674_0
numpy-base                1.23.5           py39h9cd3388_0
openjpeg                  2.4.0                h66ea3da_0
openssl                   1.1.1s               hca72f7f_0
packaging                 22.0             py39hecd8cb5_0
partd                     1.2.0              pyhd3eb1b0_1
pathspec                  0.9.0            py39hecd8cb5_0
photutils                 1.5.0            py39h15b18c7_0    astropy
pillow                    9.3.0            py39h81888ad_1
pip                       22.3.1           py39hecd8cb5_0
platformdirs              2.5.2            py39hecd8cb5_0
pluggy                    1.0.0            py39hecd8cb5_1
psutil                    5.9.0            py39hca72f7f_0
py                        1.11.0             pyhd3eb1b0_0
pyerfa                    2.0.0.1          py39h86b5767_2    astropy
pyparsing                 3.0.9            py39hecd8cb5_0
pyrsistent                0.18.0           py39hca72f7f_0
pytest                    7.1.2            py39hecd8cb5_0
pytest-arraydiff          0.3                        py_0    astropy
pytest-astropy            0.10.0             pyhd8ed1ab_0    astropy
pytest-astropy-header     0.1.2                      py_0    astropy
pytest-cov                3.0.0              pyhd3eb1b0_0
pytest-doctestplus        0.12.0             pyhd8ed1ab_0    astropy
pytest-filter-subpackage  0.1.1                      py_0    astropy
pytest-mock               3.10.0           py39hecd8cb5_0
pytest-openfiles          0.5.0                      py_0    astropy
pytest-remotedata         0.3.3              pyhd8ed1ab_0    astropy
python                    3.9.16               h218abb5_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python_abi                3.9                      2_cp39    astropy
pywavelets                1.4.1            py39h6c40b1e_0
pyyaml                    6.0              py39h6c40b1e_1
readline                  8.2                  hca72f7f_0
scikit-image              0.19.3           py39hcec6c5f_1
scikit-learn              1.2.0            py39hcec6c5f_0
scipy                     1.9.3            py39h3d31255_0
semantic_version          2.10.0             pyhd8ed1ab_0    astropy
setuptools                65.6.3           py39hecd8cb5_0
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.9                he9d5cce_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
sqlite                    3.40.1               h880c91c_0
threadpoolctl             2.2.0              pyh0d69192_0
tifffile                  2021.7.2           pyhd3eb1b0_2
tk                        8.6.12               h5d9f67b_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1            py39hecd8cb5_0
toolz                     0.12.0           py39hecd8cb5_0
tqdm                      4.64.1           py39hecd8cb5_0
typing_extensions         4.4.0            py39hecd8cb5_0
tzdata                    2022g                h04d1e81_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.10               h6c40b1e_1
yaml                      0.2.5                haf1e3a3_0
zfp                       0.5.5                he9d5cce_6
zipp                      3.11.0           py39hecd8cb5_0
zlib                      1.2.13               h4dc903c_0
zstd                      1.5.2                hcb37349_0
```

Note that `photutils` and its dependencies are listed in the output and there are no packages from `conda-forge` in the list (when using the astropy channel).

Did installing using `conda-forge` work for you?
```
conda create -n myenv python=3.9
conda activate myenv
conda install photutils -c conda-forge
```
I recommend starting from a fresh environment. Your errors clearly indicate an issue with your python environment.

**Comment by mfeldt** [comment]
You are right, the environment is messed up.  Somehow, astropy is always imported from ~/.local/lib, no matter what environment is active
