### ISSUE TITLE
photutils import failing on background.py import

### ISSUE THREAD

**Issue by hover2pi** [astropy/photutils#316]
Getting this error after running `python setup.py test`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "photutils/__init__.py", line 15, in <module>
    from .background import *
  File "photutils/background.py", line 13, in <module>
    ASTROPY_LT_1P1 = ([int(majv), int(minv)] < [1, 1])
ValueError: invalid literal for int() with base 10: '1b1'
```

**Comment by hover2pi** [comment]
Upgraded Anaconda from 1.8.0 to 2.4.1 and it works!
