### ISSUE TITLE
AttributeError: 'loggerclass' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#534]
**Forwarded from STScI Help Desk**

I need to use the photutils package for may routine in python so I followed the instruction on this link to install it:  http://photutils.readthedocs.io/en/stable/photutils/install.html
   
basically this is what I did: `conda install -c astropy photutils`
  
but now, when I ran the routine, I get an error that has nothing to do with photutils. The point is that the same routine was working just fine before I installed photutils so I don't know if I did something wrong or the installation messed with something.
  
This is the error I'm getting:
```  
  Traceback (most recent call last):
   File ".../Desktop/ACSfits/ACStable.py", line 1029, in <module>
     sel_table,warning_ap_list,wcs_strip,drc_imm,strip_imm=select_table(ap_table,name_list,vis,ext_num,n,num,path2raw,path2ref,path2photo,path2reg,warning_ap_list,path2savecat,filt)
   File ".../Desktop/ACSfits/ACStable.py", line 226, in select_table
     wcs_strip=WCS(prihdr_strip)
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/wcs/wcs.py", line 447, in __init__
     sip = self._read_sip_kw(header, wcskey=key)
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/wcs/wcs.py", line 1060, in _read_sip_kw
     log.info(message)
   File ".../anaconda3/envs/astroconda/lib/python3.5/logging/__init__.py", line 1279, in info
     self._log(INFO, msg, args, **kwargs)
   File ".../anaconda3/envs/astroconda/lib/python3.5/logging/__init__.py", line 1415, in _log
     self.handle(record)
   File ".../anaconda3/envs/astroconda/lib/python3.5/logging/__init__.py", line 1425, in handle
     self.callHandlers(record)
   File ".../anaconda3/envs/astroconda/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
     hdlr.handle(record)
   File ".../anaconda3/envs/astroconda/lib/python3.5/logging/__init__.py", line 855, in handle
     self.emit(record)
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/logger.py", line 559, in emit
     color_print(record.levelname, 'green', end='', file=stream)
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/utils/console.py", line 359, in color_print
     file = kwargs.get('file', _get_stdout())
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/utils/console.py", line 122, in _get_stdout
     if not isatty(sys_stream) or _IPython.OutStream is None:
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/utils/console.py", line 153, in isatty
     if (_IPython.OutStream is None or
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/utils/decorators.py", line 648, in __get__
     val = self.fget.__wrapped__(objtype)
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/utils/console.py", line 60, in OutStream
     cls.get_ipython()
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/utils/decorators.py", line 648, in __get__
     val = self.fget.__wrapped__(objtype)
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/utils/console.py", line 50, in get_ipython
     from IPython import get_ipython
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/IPython/__init__.py", line 49, in <module>
     from .terminal.embed import embed
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/IPython/terminal/embed.py", line 17, in <module>
     from IPython.terminal.interactiveshell import TerminalInteractiveShell
   File ".../anaconda3/envs/astroconda/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 77, in <module>
     _is_tty = (sys.stdin.isatty()) and (sys.stdout.isatty()) and  (sys.stderr.isatty())
 AttributeError: 'loggerclass' object has no attribute 'isatty'
```
Can you help me solving this problem because I'm really stuck.

c/c @larrybradley

**Comment by pllim** [comment]
False alarm. Problem solved with IPython update from 5.0 to 5.3.
