### ISSUE TITLE
Example failure for mpl 2.1 and np 1.12

### ISSUE THREAD

**Issue by bsipocz** [astropy/photutils#599]
A new failure started to show up on travis, and I can reproduce it with using the combination of numpy 1.12 with matplotlib 2.1.

Exact same install, but with mpl 2.0.2 does pass as does the combination of np 1.13 with mpl 2.1.

As this looks much like an upstream issue, as a quick and dirty workaround I suggest to use the 2.0.2 version in the travis job. If that sounds good, I can included that in the helpers update PR.

```
============================= test session starts ==============================
platform darwin -- Python 3.6.2, pytest-3.1.3, py-1.4.34, pluggy-0.4.0

Running tests with photutils version 0.4.dev2707.
Running tests in lib.macosx-10.10-x86_64-3.6/photutils docs.

Date: 2017-10-13T18:04:02

Platform: Darwin-14.5.0-x86_64-i386-64bit

Executable: /sw/bin/python3.6

Full Python Version: 
3.6.2 (default, Jul 21 2017, 17:54:08) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.12.1
Scipy: 0.19.1
Matplotlib: 2.1.0
Pandas: 0.20.3
Astropy: 2.0.2
scikit-image: 0.13.1
Using Astropy options: remote_data: none.

rootdir: /private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/photutils-test-6silcbet, inifile: setup.cfg
plugins: mpl-0.7, cov-2.5.1
collected 1099 items 

../docs/photutils/segmentation.rst F
../docs/photutils/utils.rst .

=================================== FAILURES ===================================
__________________ [doctest] docs/photutils/segmentation.rst ___________________
419     >>> labels = [1, 5, 20, 50, 75, 80]
420     >>> props = source_properties(data, segm, labels=labels,
421     ...                            background=bkg.background)
422     >>> columns = ['id', 'background_at_centroid', 'background_mean',
423     ...            'background_sum']
424     >>> tbl = properties_table(props, columns=columns)
425     >>> tbl['background_at_centroid'].info.format = '.10f'  # optional format
426     >>> tbl['background_mean'].info.format = '.10f'
427     >>> tbl['background_sum'].info.format = '.10f'
428     >>> print(tbl)
UNEXPECTED EXCEPTION: AttributeError("'numpy.float64' object has no attribute 'value'",)
Traceback (most recent call last):

  File "/sw/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest segmentation.rst[81]>", line 1, in <module>

  File "/sw/lib/python3.6/site-packages/astropy/table/table.py", line 878, in __unicode__
    return '\n'.join(self.pformat())

  File "/sw/lib/python3.6/site-packages/astropy/table/table.py", line 1177, in pformat
    tableid=tableid, tableclass=tableclass, align=align)

  File "/sw/lib/python3.6/site-packages/astropy/table/pprint.py", line 541, in _pformat_table
    align=align_)

  File "/sw/lib/python3.6/site-packages/astropy/table/pprint.py", line 254, in _pformat_col
    col_strs = list(col_strs_iter)

  File "/sw/lib/python3.6/site-packages/astropy/table/pprint.py", line 455, in _pformat_col_iter
    col_str = format_func(col_format, col[i])

  File "/sw/lib/python3.6/site-packages/astropy/table/pprint.py", line 41, in <lambda>
    else format_func(format_, val))

  File "/sw/lib/python3.6/site-packages/astropy/units/quantity.py", line 135, in <lambda>
    yield lambda format_, val: format(val.value, format_)

AttributeError: 'numpy.float64' object has no attribute 'value'

/private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/photutils-test-6silcbet/docs/photutils/segmentation.rst:428: UnexpectedException
======== 1 failed, 1094 passed, 2 skipped, 2 xfailed in 159.39 seconds =========
```

**Comment by bsipocz** [comment]
Actually this is a false positive, the issue is detailed and fixed in #598.

**Comment by larrybradley** [comment]
Yep, this the astropy table column format bug showing up again.

**Comment by bsipocz** [comment]
It really badly tricked me, correlated so well with the local version numbers...
