### ISSUE TITLE
import error for DAOStarFinder and IRAFStarFinder

### ISSUE THREAD

**Issue by stefanocovino** [astropy/photutils#633]
I have just updated photutils to version 0.4 (astropy is version 2.0.2) with python3.6 (anaconda).

Now, if I try to execute something like:

from photutils import DAOStarFinder

I get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/photutils-0.4-py3.6-linux-x86_64.egg/photutils/__init__.py", line 17, in <module>
    from .background import *      # noqa
  File "/usr/local/anaconda3/lib/python3.6/site-packages/photutils-0.4-py3.6-linux-x86_64.egg/photutils/background/__init__.py", line 7, in <module>
    from .core import *             # noqa
  File "/usr/local/anaconda3/lib/python3.6/site-packages/photutils-0.4-py3.6-linux-x86_64.egg/photutils/background/core.py", line 15, in <module>
    from astropy.stats import (SigmaClip, biweight_location, biweight_scale,
ImportError: cannot import name 'SigmaClip'

The same happens for IRAFStarFinder.

Going back to photutils 0.3.2 everything seems to be fine.

Thanks for your attention,
  Stefano

**Comment by stefanocovino** [comment]
Actually, it is not a problem of photutils but it seems related to different astropy installations.

  S.

**Comment by larrybradley** [comment]
Yes, `photutils 0.4` requires `astropy >= 2.0`.  Make sure you have updated `astropy` in your current environment.
