### ISSUE TITLE
Installing in Windows

### ISSUE THREAD

**Issue by astropatel** [astropy/photutils#654]
I am trying to install photutils on windows, with a canopy environment. 

After manually downloading and running "python setup.py install", I get the following errors:

```
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying photutils\_compiler.c -> build\lib.win-amd64-2.7\photutils
running build_ext
building 'photutils._compiler' extension
c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\anakha272\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.3.0.1715.win-x86_64\include -IC:\users\anakha272\appdata\local\enthought\canopy\user\PC /Tcphotutils\_compiler.c /Fobuild\temp.win-amd64-2.7\Release\photutils\_compiler.obj
_compiler.c
photutils\_compiler.c(67) : warning C4005: 'COMPILER' : macro redefinition
        c:\users\anakha272\appdata\local\enthought\canopy\app\appdata\canopy-1.3.0.1715.win-x86_64\include\pyconfig.h(207) : see previous definition of 'COMPILER'
c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\users\anakha272\appdata\local\enthought\canopy\user\libs /LIBPATH:C:\users\anakha272\appdata\local\enthought\canopy\user\PCbuild\amd64 /EXPORT:init_compiler build\temp.win-amd64-2.7\Release\photutils\_compiler.obj /OUT:build\lib.win-amd64-2.7\photutils\_compiler.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\photutils\_compiler.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\photutils\_compiler.pyd.manifest
LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'
error: command '"c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\link.exe"' failed with exit status 1104
```

I don't understand what is going wrong. After this, I try to import photutils and I get the following error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-9345b59bbc41> in <module>()
----> 1 import photutils

C:\Users\anakha272\AppData\Local\Enthought\Canopy\User\Lib\site-packages\photutils-master\photutils\__init__.py in <module>()
     14
     15 if not _ASTROPY_SETUP_:            # noqa
---> 16     from .aperture import *        # noqa
     17     from .background import *      # noqa
     18     from .centroids import *       # noqa

C:\Users\anakha272\AppData\Local\Enthought\Canopy\User\Lib\site-packages\photutils-master\photutils\aperture\__init__.py in <module
>()
      6
      7 from .bounding_box import *    # noqa
----> 8 from .circle import *          # noqa
      9 from .core import *            # noqa
     10 from .ellipse import *         # noqa

C:\Users\anakha272\AppData\Local\Enthought\Canopy\User\Lib\site-packages\photutils-master\photutils\aperture\circle.py in <module>(
)
      9 from .bounding_box import BoundingBox
     10 from .mask import ApertureMask
---> 11 from ..geometry import circular_overlap_grid
     12 from ..utils.wcs_helpers import assert_angle_or_pixel
     13

C:\Users\anakha272\AppData\Local\Enthought\Canopy\User\Lib\site-packages\photutils-master\photutils\geometry\__init__.py in <module
>()
      4 """
      5
----> 6 from .circular_overlap import *       # noqa
      7 from .elliptical_overlap import *     # noqa
      8 from .rectangular_overlap import *    # noqa

ImportError: No module named circular_overlap

```

I don't know if those two are related. Any help would be appreciated.

I am running python 2.7.

**Comment by larrybradley** [comment]
`Photutils` requires a C compiler and `Cython` to be installed.  I don't have a Windows machine, but your error message seems to indicate a problem with your C complier.  This may help (from a quick Google):

https://stackoverflow.com/questions/6228112/link-fatal-error-lnk1104-cannot-open-file-msvcrtd-lib

As an alternative, I would suggest using the `conda` package manager:  https://conda.io/miniconda.html

**Comment by larrybradley** [comment]
Please reopen if you are still having issues.

**Comment by noi26** [comment]
Hello, having similar issue.. 
tried to run very basic option of the package on PyCharm:
```
import numpy as np
from photutils import datasets
hdu=datasets.load_star_image('image.fits')
image = hdu.data[500:700, 500:700].astype(float)
image -= np.median(image)
```
After running it i got an error:
`Traceback (most recent call last):
  File "C:/Users/......", line 3, in <module>
    from photutils import datasets
  File "C:\Users\......", line 19, in <module>
    from .aperture import *  # noqa
  File "C:\Users\.........", line 7, in <module>
    from .circle import *  # noqa
  File "C:\Users......", line 15, in <module>
    from ..geometry import circular_overlap_grid
  File "C:\Users\.......", line 6, in <module>
    from .circular_overlap import *  # noqa
ModuleNotFoundError: No module named 'photutils.geometry.circular_overlap'
`
I have installed photutils with conda.. tried to uninstall and install again, and no change, any suggestions? 

Thanks,
Noi <3

**Comment by larrybradley** [comment]
@noi26 Are you by chance starting python from within a directory containing the `photutils` source code?  If so, that will not work.

**Comment by noi26** [comment]
@larrybradley Yes. you right. Thank you
