### ISSUE TITLE
Issue with deblend_sources() in 0.7.dev3641

### ISSUE THREAD

**Issue by stephenmwilkins** [astropy/photutils#880]
Hello,

I switched to 0.7.dev because of something I assume is related with issue #808 (deblending would fail for a source (512, 1024, or 2048 it would seem) however I'm now experiencing a new error:
ValueError: The segmentation image must contain at least one non-zero pixel.

I haven't done any thorough exploration yet, but might be able to later.

Steve

**Comment by larrybradley** [comment]
Thanks, @stephenmwilkins.  Can you provide an example so that I can take a look?

**Comment by stephenmwilkins** [comment]
Hey @larrybradley this appears to have been fixed in the most recent release. Thanks for whatever it was and thanks for all the work on the module!

**Comment by stephenmwilkins** [comment]
Sorry, spoke too soon, another test revealed the same error.

```
import numpy as np
from photutils import detect_sources
from photutils import deblend_sources


threshold = 2.0
npixels = 5.0

data = np.load('test.npy')

segm = detect_sources(data, threshold, npixels = npixels)  
segm_deblend = deblend_sources(data, segm, npixels=npixels, nlevels=32)

```

results in:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    segm_deblend = deblend_sources(data, segm, npixels=npixels, nlevels=32)
  File "/anaconda3/lib/python3.7/site-packages/photutils/segmentation/deblend.py", line 128, in deblend_sources
    contrast=contrast, mode=mode, connectivity=connectivity)
  File "/anaconda3/lib/python3.7/site-packages/photutils/segmentation/deblend.py", line 288, in _deblend_source
    segm_tree[j].remove_labels(intersect_labels)
  File "/anaconda3/lib/python3.7/site-packages/photutils/segmentation/core.py", line 1017, in remove_labels
    self.reassign_label(labels, new_label=0)
  File "/anaconda3/lib/python3.7/site-packages/photutils/segmentation/core.py", line 680, in reassign_label
    self.reassign_labels(label, new_label, relabel=relabel)
  File "/anaconda3/lib/python3.7/site-packages/photutils/segmentation/core.py", line 764, in reassign_labels
    self.data = idx[self.data]
  File "/anaconda3/lib/python3.7/site-packages/photutils/segmentation/core.py", line 290, in data
    raise ValueError('The segmentation image must contain at least '
ValueError: The segmentation image must contain at least one non-zero pixel.

test.py at https://www.dropbox.com/s/f0zrqx7a6f2158t/test.npy?dl=0

**Comment by larrybradley** [comment]
Many thanks for the example/data.  I should have a fix for this tomorrow.
