### ISSUE TITLE
Can't import Photutils

### ISSUE THREAD

**Issue by franzbinder** [astropy/photutils#976]
I installed photutils on Ubuntu and it rasied no error, but if i try to import it i get :
 this error for python 2 and 3 (different ones):
franz@franz-VirtualBox:~/photutils$ python
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import photutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "photutils/__init__.py", line 19, in <module>
    from .aperture import *  # noqa
  File "photutils/aperture/__init__.py", line 7, in <module>
    from .circle import *  # noqa
  File "photutils/aperture/circle.py", line 13, in <module>
    from .core import PixelAperture, SkyAperture
  File "photutils/aperture/core.py", line 27
    class Aperture(metaclass=abc.ABCMeta):
                            ^
SyntaxError: invalid syntax
>>> exit()
franz@franz-VirtualBox:~/photutils$ python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import photutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/franz/photutils/photutils/__init__.py", line 19, in <module>
    from .aperture import *  # noqa
  File "/home/franz/photutils/photutils/aperture/__init__.py", line 7, in <module>
    from .circle import *  # noqa
  File "/home/franz/photutils/photutils/aperture/circle.py", line 15, in <module>
    from ..geometry import circular_overlap_grid
  File "/home/franz/photutils/photutils/geometry/__init__.py", line 6, in <module>
    from .circular_overlap import *  # noqa
ModuleNotFoundError: No module named 'photutils.geometry.circular_overlap'

in pycharm i get this error:

Traceback (most recent call last):
  File "/home/franz/PycharmProjects/untitled/CCDPipleline.py", line 7, in <module>
    import photutils
  File "/usr/local/lib/python3.6/dist-packages/photutils/__init__.py", line 19, in <module>
    from .aperture import *  # noqa
  File "/usr/local/lib/python3.6/dist-packages/photutils/aperture/__init__.py", line 7, in <module>
    from .circle import *  # noqa
  File "/usr/local/lib/python3.6/dist-packages/photutils/aperture/circle.py", line 13, in <module>
    from .core import PixelAperture, SkyAperture
  File "/usr/local/lib/python3.6/dist-packages/photutils/aperture/core.py", line 104, in <module>
    class PixelAperture(Aperture):
  File "/usr/local/lib/python3.6/dist-packages/photutils/aperture/core.py", line 369, in PixelAperture
    subpixels=5, unit=None):
  File "/usr/lib/python3/dist-packages/astropy/utils/decorators.py", line 444, in decorator
    '.'.format(new_name[i]))
TypeError: "None" was not specified in the function signature. If it was meant to be part of "**kwargs" then set "arg_in_kwargs" to "True".

any help would be appriciated!

**Comment by franzbinder** [comment]
Also i get this error when trying to install it : 
franz@franz-VirtualBox:~/photutils$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import builtins
ImportError: No module named builtins


but if i run :  

franz@franz-VirtualBox:~/photutils$ pip install photutils
Collecting photutils
Collecting astropy (from photutils)
  Using cached https://files.pythonhosted.org/packages/bc/ad/f108a5bd8aba3d5f5d4d5090a8802a78e4e50e8150cb090b6d43b399db5f/astropy-2.0.15-cp27-cp27mu-manylinux1_x86_64.whl
Collecting six (from photutils)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pytest<3.7,>=2.8 (from astropy->photutils)
  Using cached https://files.pythonhosted.org/packages/d8/e9/73246a565c34c5f203dd78bc2382e0e93aa7a249cdaeba709099eb1bc701/pytest-3.6.4-py2.py3-none-any.whl
Collecting numpy>=1.9.0 (from astropy->photutils)
  Using cached https://files.pythonhosted.org/packages/d7/b1/3367ea1f372957f97a6752ec725b87886e12af1415216feec9067e31df70/numpy-1.16.5-cp27-cp27mu-manylinux1_x86_64.whl
Collecting setuptools (from pytest<3.7,>=2.8->astropy->photutils)
  Using cached https://files.pythonhosted.org/packages/6a/9a/50fadfd53ec909e4399b67c74cc7f4e883488035cfcdb90b685758fa8b34/setuptools-41.4.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest<3.7,>=2.8->astropy->photutils)
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest<3.7,>=2.8->astropy->photutils)
  Using cached https://files.pythonhosted.org/packages/2f/9d/dcfe59e213093695f108508af1214cf9cd95cc5489e46877ec5cb56369e5/more_itertools-5.0.0-py2-none-any.whl
Collecting funcsigs; python_version < "3.0" (from pytest<3.7,>=2.8->astropy->photutils)
  Using cached https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest<3.7,>=2.8->astropy->photutils)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting atomicwrites>=1.0 (from pytest<3.7,>=2.8->astropy->photutils)
  Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting pluggy<0.8,>=0.5 (from pytest<3.7,>=2.8->astropy->photutils)
  Using cached https://files.pythonhosted.org/packages/f5/f1/5a93c118663896d83f7bcbfb7f657ce1d0c0d617e6b4a443a53abcc658ca/pluggy-0.7.1-py2.py3-none-any.whl
Installing collected packages: setuptools, py, six, more-itertools, funcsigs, attrs, atomicwrites, pluggy, pytest, numpy, astropy, photutils
Successfully installed astropy-2.0.15 atomicwrites-1.3.0 attrs-19.3.0 funcsigs-1.0.2 more-itertools-5.0.0 numpy-1.16.5 photutils-0.4.1 pluggy-0.7.1 py-1.8.0 pytest-3.6.4 setuptools-41.4.0 six-1.12.0
i don't understand why!

**Comment by franzbinder** [comment]
i fxed the issue by upgrading astropy to 3.2.2
